variable "vpc_name" {}
variable "cidr_block" {}
variable "public_subnet1_cidr" {}
variable "public_subnet1_name" {}
variable "public_subnet2_cidr" {}
variable "public_subnet2_name" {}
variable "public_subnet3_cidr" {}
variable "public_subnet3_name" {}
variable "private_subnet1_cidr" {}
variable "private_subnet1_name" {}
variable "private_subnet2_cidr" {}
variable "private_subnet2_name" {}
variable "Main_Routing_Table" {}
